version: '3.7'
services:
  sybil-network:
    container_name: sybil-network
    image: sybil-network:nightly
    ports:
        - "3000:3000"
    # You may also create a .env file in the same folder as the docker-compose.yml file
    environment:
        LOG_LEVEL: info
        MAXMIND_LICENSE_KEY:
        PUBLIC_URL: "http://localhost:3000"
        IP2LOCATION_DOWNLOAD_TOKEN: 
    volumes:
        - ./database.sqlite:/app/database.sqlite 
        # - ./node_modules/geoip-lite/data:/app/node_modules/geoip-lite/data
        - maxmind_data:/app/node_modules/geoip-lite/data
        # - ./IP2LOCATION-LITE-ASN.IPV6.BIN:/app/IP2LOCATION-LITE-ASN.IPV6.BIN
        - ip2location_data:/app/IP2LOCATION-LITE-ASN.IPV6.BIN

volumes:
    maxmind_data:
    ip2location_data: