# .github/workflows/docker-deploy.yml

name: Deploy Unified Dante Docker Image

on:
  push:
    # Trigger only when package.json is modified
    paths:
      - "federated-container/tpn_dante.Dockerfile"
    branches:
      - main
      - development

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      
      # 1. Checkout with enough history to compare previous commit
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 2  # Need previous commit for diff

      # 2. Check if the version property in package.json changed
      - name: Check version change
        id: version_check
        run: |
          # Extract current version from the current package.json
          CUR_VERSION=$(jq -r .version federated-container/package.json)
          echo "Current version: $CUR_VERSION"
          echo "version=$CUR_VERSION" >> $GITHUB_OUTPUT
        shell: bash

      # 3. Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # 4. Build and push the Docker image with the new version tag (only if version changed), add -dev for development branch
      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: ./federated-container/
          file: ./federated-container/tpn_dante.Dockerfile
          push: true
          tags: |
            taofuprotocol/tpn-dante:${{ steps.version_check.outputs.version }}${{ github.ref == 'refs/heads/development' && '-dev' || '' }}
            taofuprotocol/tpn-dante:latest${{ github.ref == 'refs/heads/development' && '-dev'  || '' }}
